from test_centralised_vcs import CentralisedVCSTest
from test_change_management import ChangeManagementTestCase
from test_chunk import ChunkTest
from test_feature import FeatureTest
from test_software_project import SoftwareProjectTestCase
from test_softwaresystem import SoftwareSystemTest
from test_test import TestTest
from test_test_driven_development import TestDrivenDevelopmentTestCase
from test_team import TDDDevelopmentTeamTestCase

#from regression_test_tdd_developer import TDDDeveloperRegressionTestCase
#from regression_test_waterfall import WaterfallRegressionTestCase
