# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches:
      - master

jobs:
  upgrade_to_Python3:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: "Upgrade to Python3"
        uses: cclauss/Upgrade-to-Python3@master
      - name: Commit files
        run: |
              git config --local user.email "2314993w@student.gla.ac.uk"
              git config --local user.name "Jack Watters"
              git commit -m "Add changes" -a
      - name: Push changes
        uses: JackWatters/create-pull-request@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: 'py3-addendum'
